### ISSUE TITLE
DexIndexOverflowException Android Studio

### ISSUE THREAD

**Issue by gautamverma** [7digital/7digital-Android-SDK#13]
I have tried both the jars i.e 7digital-android-sdk-v0.93 and 7digital-android-sdk-v0.93-withDependencies.jar. In the first case it gives me exception dependencies not found so when i manually add all the dependencies 

> compile('org.simpleframework:simple-xml:2.7.1') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.0'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.5.0'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.5.0'
    compile 'joda-time:joda-time:2.7'
    compile 'com.mcxiaoke.volley:library:1.0.10'

It gives me the exception 

> UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:283)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
Information:BUILD FAILED

So i tried the other way round i.e  added the jar with dependencies. The it showed error 

> import com.android.volley.RequestQueue;
import com.android.volley.toolbox.ImageLoader;
import com.android.volley.toolbox.Volley;

These classes don't exist. So i added compile 'com.mcxiaoke.volley:library:1.0.10' and ended with the same above dex Overflow Exception. Any help on how to solve this issues.

I have already tried adding one by one, then either it gives JavaClassNotFound Exception or Dex OverFlow Error.

**Comment by juliusspencer** [comment]
```com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536```
It looks like you've hit the dex limit and need to use Multidex if you need all the libraries in the application. See:
https://developer.android.com/tools/building/multidex.html
