### ISSUE TITLE
Android sample app and tests don't compile

### ISSUE THREAD

**Issue by YmlMark** [7digital/7digital-Android-SDK#14]
Both the sample application and the SDK tests don't compile because the calling signature of getTrackPreview() doesn't match its definition in the SDK.

/Users/mark.rosenberg/AndroidStudioProjects/7digital-Android-SDK/sdk/src/androidTest/java/uk.co.sevendigital.android.sdk.test/api.request/preview/TSDIGetTrackPreviewRequest.java
Error:(63, 42) error: incompatible types: ServerAccessToken cannot be converted to String
Error:(77, 25) error: no suitable method found for getTrackPreview(String)
method SDIApi.Streaming.getTrackPreview(String,String) is not applicable
(actual and formal argument lists differ in length)
method SDIApi.Streaming.getTrackPreview(ServerAccessToken,String,String) is not applicable
(actual and formal argument lists differ in length)

Constants.java is empty, and providing appKey and appSecret members as suggested by the documentation, is apparently no longer needed as well.

**Comment by juliusspencer** [comment]
Fixed; thank you for the detail.
