### ISSUE TITLE
Authorization error while try to stream the song

### ISSUE THREAD

**Issue by Dhrupal** [7digital/7digital-Android-SDK#8]
I am getting track id in the sample application , now I want to stream this song. My code look like below.

sServerToken = new SDIServerUtil.ServerAccessToken(Constants.OAUTH_CONSUMER_KEY, Constants.OAUTH_CONSUMER_SECRET);
String token= sServerToken.getToken();
SDIGetTrackPreviewRequest.Result result= api.streaming().getTrackPreview(sServerToken, trackId);

But it throws authorization error. Log is like below:

01-09 10:10:32.467    6402-6476/uk.co.sevendigital.android.sdk.sample E/Volley﹕ [420] BasicNetwork.performRequest: Unexpected response code 401 for http://previews.7digital.com/clip/39704503?oauth_consumer_key=7d49xhs4ywuw&oauth_nonce=3251829979354847678&oauth_signature=f0oz1XXzvNmoH8uMVSF%2FMd5vmBk%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1420778501&oauth_token=7d49xhs4ywuw
01-09 10:10:33.069    6402-6476/uk.co.sevendigital.android.sdk.sample E/Volley﹕ [420] BasicNetwork.performRequest: Unexpected response code 401 for http://previews.7digital.com/clip/39704503?oauth_consumer_key=7d49xhs4ywuw&oauth_nonce=3251829979354847678&oauth_signature=f0oz1XXzvNmoH8uMVSF%2FMd5vmBk%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1420778501&oauth_token=7d49xhs4ywuw
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ java.util.concurrent.ExecutionException: com.android.volley.AuthFailureError
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:117)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:88)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at uk.co.sevendigital.android.sdk.util.VolleyUtil.executeStringRequest(VolleyUtil.java:51)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at uk.co.sevendigital.android.sdk.api.request.preview.SDIGetTrackPreviewRequest.execute(SDIGetTrackPreviewRequest.java:83)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at uk.co.sevendigital.android.sdk.api.SDIApi$Streaming.getTrackPreview(SDIApi.java:543)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at uk.co.sevendigital.android.sdk.sample.fragment.detail.TrackDetailFragment$TrackDetailAsync.doInBackground(TrackDetailFragment.java:146)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at uk.co.sevendigital.android.sdk.sample.fragment.detail.TrackDetailFragment$TrackDetailAsync.doInBackground(TrackDetailFragment.java:120)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
01-09 10:10:50.696    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ Caused by: com.android.volley.AuthFailureError
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:153)
01-09 10:10:50.697    6402-6582/uk.co.sevendigital.android.sdk.sample W/System.err﹕ at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)

**Comment by ling0star** [comment]
Issue resolved
